const DEFAULT_MODEL_CONCURRENCY = 20

const MAX_CONCURRENT_AGENTS = Number(
  process.env['MAX_CONCURRENT_AGENTS'] ?? DEFAULT_MODEL_CONCURRENCY,
)

const MAX_PARALLEL_MODULE_AGENTS = Number(
  process.env['MAX_PARALLEL_MODULE_AGENTS'] ?? DEFAULT_MODEL_CONCURRENCY,
)

const MODULE_FEEDBACK_MAX = Number(process.env['MODULE_FEEDBACK_MAX'] ?? 2)

const ENABLE_GLOBAL_REPAIR = process.env['ENABLE_GLOBAL_REPAIR'] === 'true'

const GLOBAL_REPAIR_MAX_DIFF_REGRESSION = Number(
  process.env['GLOBAL_REPAIR_MAX_DIFF_REGRESSION'] ?? 0.001,
)

const MAX_AGENT_TURN_COMMANDS = Number(
  process.env['MAX_AGENT_TURN_COMMANDS'] ?? 0,
)

const MAX_AGENT_TURN_VERIFY_RUNS = Number(
  process.env['MAX_AGENT_TURN_VERIFY_RUNS'] ?? 4,
)

const MAX_AGENT_STALLED_VERIFY_RUNS = Number(
  process.env['MAX_AGENT_STALLED_VERIFY_RUNS'] ?? 8,
)

const AGENT_VERIFY_MIN_IMPROVEMENT = Number(
  process.env['AGENT_VERIFY_MIN_IMPROVEMENT'] ?? 0.001,
)

const MIN_AGENT_VERIFY_RUNS_BEFORE_STALL_STOP = Number(
  process.env['MIN_AGENT_VERIFY_RUNS_BEFORE_STALL_STOP'] ?? 12,
)

export {
  AGENT_VERIFY_MIN_IMPROVEMENT,
  ENABLE_GLOBAL_REPAIR,
  GLOBAL_REPAIR_MAX_DIFF_REGRESSION,
  MAX_AGENT_STALLED_VERIFY_RUNS,
  MAX_AGENT_TURN_COMMANDS,
  MAX_AGENT_TURN_VERIFY_RUNS,
  MAX_CONCURRENT_AGENTS,
  MAX_PARALLEL_MODULE_AGENTS,
  MIN_AGENT_VERIFY_RUNS_BEFORE_STALL_STOP,
  MODULE_FEEDBACK_MAX,
}
