import { compileComponentLibrary } from "../pipeline/component-library/compiler.js";
import type { ComponentLibraryFramework } from "../core/component-library/types.js";

const VALUE_FLAGS = new Set([
  "--framework",
  "--source-dir",
  "--url",
]);

const parseFlagValue = (args: string[], flag: string) => {
  const inlineArg = args.find((arg) => arg.startsWith(`${flag}=`));
  if (inlineArg) return inlineArg.slice(flag.length + 1);
  const flagIndex = args.indexOf(flag);
  if (flagIndex >= 0) return args[flagIndex + 1];
  return undefined;
};

const parseFramework = (value: unknown): ComponentLibraryFramework => {
  const normalized = String(value ?? "").trim().toLowerCase();
  if (normalized === "vue" || normalized === "react") return normalized;
  throw new Error("Missing or invalid --framework <vue|react>");
};

const hasHelp = (args: string[]) =>
  args.includes("--help") || args.includes("-h");

const printUsage = () => {
  console.log(
    [
      "Usage:",
      "  pnpm exec tsx src/cli/compile-component-library.ts --source-dir <path> --framework <vue|react> [--force]",
      "  pnpm exec tsx src/cli/compile-component-library.ts --url <git-url> --framework <vue|react> [--force]",
      "",
      "Notes:",
      "  - The source is copied/cloned into workspace/component-libraries/<id>/source.",
      "  - component-library.json is generated by the configured LLM and then schema/path validated.",
      "  - Compile only generates the descriptor; dependencies are installed lazily (via the install API or at merge time), not during compile.",
    ].join("\n"),
  );
};

const assertNoUnknownValueFlag = (args: string[]) => {
  for (const flag of VALUE_FLAGS) {
    const index = args.indexOf(flag);
    if (index >= 0 && !args[index + 1]) {
      throw new Error(`Missing value for ${flag}`);
    }
  }
};

const main = async () => {
  const args = process.argv.slice(2);
  if (hasHelp(args)) {
    printUsage();
    return;
  }
  assertNoUnknownValueFlag(args);
  const framework = parseFramework(parseFlagValue(args, "--framework"));
  const result = await compileComponentLibrary({
    force: args.includes("--force") || args.includes("force"),
    framework,
    sourceDir: parseFlagValue(args, "--source-dir"),
    url: parseFlagValue(args, "--url"),
  });

  console.log(`Component library compiled: ${result.library.id}`);
  console.log(`Name: ${result.library.name}`);
  console.log(`Framework: ${result.library.framework}`);
  console.log(`Components: ${result.library.componentCount}`);
  console.log(`Source dir: ${result.sourceDir}`);
  console.log(`Descriptor: ${result.descriptorPath}`);
  if (result.library.install?.status) {
    console.log(`Install: ${result.library.install.status}`);
  }
};

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
